id: P004221
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG24038
  title: སྡེ་དགེ་རྒྱལ་རབས།
  author: ''
  volumes:
    3b0888da4fc541a8a0e2eaac4b20ea39:
      image_group_id: I1KG24192
      title: ''
      volume_number: 1
      total_pages: 162
