id: IC51144DF
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-23T12:01:14+00:00'
last_modified: '2022-06-07T21:11:01.290823+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG24038
  title: སྡེ་དགེ་རྒྱལ་རབས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    245B:
      image_group_id: I1KG24192
      title: ''
      total_pages: 162
      order: 1
      base_file: 245B.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
